#! /usr/bin/python3

import sys
import os
import subprocess

current_branch = subprocess.Popen(["git","branch","--show-current"], stdout=subprocess.PIPE).communicate()[0].decode('utf-8')[:-1];

os.system(f'git pull origin {current_branch}');
